---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 4f31c471c30e170984ca26b2744a83b4f5da8d6b
    app.quarkus.io/build-timestamp: 2023-06-08 - 23:35:06 +0000
  labels:
    app.kubernetes.io/version: 1.37.0.Final
    app.kubernetes.io/name: product-version
  name: product-version
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.37.0.Final
      app.kubernetes.io/name: product-version
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 4f31c471c30e170984ca26b2744a83b4f5da8d6b
        app.quarkus.io/build-timestamp: 2023-06-08 - 23:35:06 +0000
      labels:
        app.kubernetes.io/version: 1.37.0.Final
        app.kubernetes.io/name: product-version
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: melke/product-version:1.37.0.Final
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: product-version
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 4f31c471c30e170984ca26b2744a83b4f5da8d6b
    app.quarkus.io/build-timestamp: 2023-06-08 - 23:35:06 +0000
  labels:
    app.kubernetes.io/name: product-version
    app.kubernetes.io/version: 1.37.0.Final
  name: product-version
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: product-version
    app.kubernetes.io/version: 1.37.0.Final
  type: ClusterIP
